### ISSUE TITLE
Code art for the masses

### ISSUE THREAD

**Issue by ThisIsJohnBrown** [nodeconf/US-CFP#41]
I have been giving talks at conferences over the last few months or so all about using Javascript and Node to make fun visual things, both in the browser and in the physical world. The talks are always very well received with a good track record of having people start doing some code art and thinking about code differently. [Here’s an example talk](https://www.youtube.com/watch?v=kovJHzQNsg0). My coding partner and I have a ton of work using Node to make some very expressive pieces.

We’re in Portland, OR. Locally to you, there’s a great community across the river in SF called [Gray Area](http://www.meetup.com/GrayArea/). They’re generally more about Processing and OpenFrameworks, but there may be some local JS artists that could give a good talk.

I love having the sort of talks that aren’t necessarily driven by live coding or picking up a specific skill you can take back home and integrate into your process the next day. Soft skills and stories and art make for good mixins at tech conferences.

**Comment by mikeal** [comment]
I've been trying to find interesting people that have been doing art with node (most people doing JS art are doing amazing art with front end tech). All pointers to repos and people are very appreciated.

**Comment by jedireza** [comment]
@mikeal have you seen http://cabbi.bo/ before? I stumbled on it randomly last week since I follow [@johnnyscript](https://twitter.com/johnnyscript).

**Comment by NHQ** [comment]
@cabbibo does amazing webGL(SL) stuff, also VR.  Back-end art?  Perhaps some kind of interactive spectacle...

**Comment by cabbibo** [comment]
Hey There @NHQ and @jedireza 

First off, thanks for the kind words :) 
I've found what @mikeal says to be true for the most part. That the front end is where most of the art happens. People like @hughsk are doing some interesting stuff using back end to help make glsl / npm code editors, but in general its limited to front end. ( and i think that he might already be talking at nodeconf ! )

That being said, I don't think this is for any reason aside from the fact that most of us either suck, or don't want to deal with a back end. Also, I think the messages coming from a front end presentation about art are widely applicable, as can be seen by the make art not apps talk. As another example:
Heres a link  to a talk I did a while ago:  https://www.youtube.com/watch?v=op6uYO_HxIU

Its not so much about technology you use, as much as the recognition that we as programmers have the ability to literally create ANYTHING, and we should look towards that superpower with respect / reverance...

:)

**Comment by NHQ** [comment]
Yeah it's not like there is no back end art making per se.  It allows us to demo live to an audience, handle user input, create collaborative experiences.  That networking is pretty simply done, until you need to scale it.  That's why we have twitch.tv and co., cuz that scaling is expensive and difficult.

A talk on this subject could be using node/io to create basic, collaborative, user-exchange streams, like sharing, pinging, heartbeats, 1-to-many, many-to-1, etc, over websockets.  Or tips and tricks for combining front and back end computations to create seamless, high performance experiences, a la networked games.

But yeah we do this all for the browser, to create interfaces, and bring it to the masses.  

I do imagine creating interfaces for machine learning feedback, which could lead to novel and unique artistic compositions.  But io.js would only handle the I/O, probably not the ML.  Ask me again it in a few years  ;^)

I'd like to see some super low level JS (sub OS), which @hughsk's work could lead to, iirc.  I would love to be able to do straight DSP at that level, out to a video/sound card.

**Comment by hughsk** [comment]
Gray Area would definitely be worth checking out – they're just over in the Mission ([full site here](http://grayarea.org/)). @mganucheau may have some good recommendations :)

There's a bunch of projects that are quietly using Node as networking glue in installations, or for bot art. For most of these projects, Node is one tool of many. If the [Darknet Shopper](http://www.theguardian.com/technology/2014/dec/05/software-bot-darknet-shopping-spree-random-shopper) was made using Node that'd make for an awesome talk. Or maybe @dariusk, who made the Amazon Random Shopper that inspired it, along with a bunch of cool [bots](http://tinysubversions.com/projects/)?

**Comment by mikeal** [comment]
As you may have seen we had to cancel the speaking event at the [Fox Theatre](https://medium.com/@mikeal/nodeconf-fox-theatre-event-cancelled-67bf6b3de4dc).

You're welcome to join us at Walker Creek Ranch for [NodeConf Adventure](https://ti.to/nodeconf/adventure) which is an un-conference with attendee driven worksshops and discussion sessions. If you'd like to adapt this topic or any other idea to that format and you're planning on attending just log an issue in the [Adventure repo](https://github.com/nodeconf/Adventure-UNCONF).
